### ISSUE TITLE
What happened to version 0.7.8

### ISSUE THREAD

**Issue by spuder** [deric/puppet-zookeeper#154]
I have puppet module 0.7.8 installed and noticed that it is no longer listed on github or in the forge. What happened to it? I don't want to downgrade to 0.7.7

Update:

I can confirm that I am not crazy, there was a 0.7.8 at one point in time.
![Screenshot 2020-06-24 13 17 34](https://user-images.githubusercontent.com/242382/85617920-3e139900-b61d-11ea-8d76-05a015e7ae85.png)

**Comment by deric** [comment]
The bump commit is generated by [puppet-blacksmith](https://github.com/voxpupuli/puppet-blacksmith). After finalizing a release e.g. `0.7.7` and uploading it to the Forge, `master` branch contains future release version is `metadata.json`. It should  be called `0.7.8-dev` or `0.7.8-unrealeased`. I know many people find this confusing... Since `1.0.0` the release should be done via CI.
